
batch_size: 16

data:
  path: "data/ESC-50-master"
  sample_rate: 8000
  train_folds: [1, 2, 3, 4]
  test_folds: [5]

model:
  n_classes: 50

optim:
  lr: 1e-4

trainer:
  gpus: 1
  fast_dev_run: False
  max_epochs: 5