FROM alpine:3.10

RUN apt-get update && \
    apt-get upgrade -y

WORKDIR /reprodl
COPY . /reprodl

RUN pip install -r requirements.txt
RUN apt-get install -y libsndfile1-dev # torchaudio

ENTRYPOINT python -m unittest discover -p "test_*.py"