#!/bin/sh
echo "Running pre-commit unit testing"

python -m unittest discover -p "test_*.py"

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Tests must pass before commit!"
 exit 1
fi 

isort --profile black .
black .
flake8 . --count --select=B9

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 echo "Code must be correctly linted before commit!"
 exit 1
fi 